### PR TITLE
Update jena to version 4.10

### PR DESCRIPTION
**Pull request by asajim**

### CODE REVIEW

**Comment by HolgerKnublauch** [comment]
Thanks!

**Comment by asajim** [comment]
@HolgerKnublauch no problem. Can you create a new release, please?

**Comment by HolgerKnublauch** [comment]
I wish it was that easy. The last time I made a release I was on a different machine. Now on the (new) Mac I would need to reinstall all this GPG stuff with keys etc.

Would you want to become a co-owner of the project here and do such things moving forward?

**Comment by asajim** [comment]
@HolgerKnublauch Yes I would to. Please let me know if you need something else from me

**Comment by HolgerKnublauch** [comment]
Thanks a lot for your offer. I have meanwhile asked around on a long-term solution to the maintenance of this repo and @ashleycaselli has volunteered to be the maintainer. He is planning to work on a new official release.

**Comment by ashleycaselli** [comment]
@asajim I'm already working on the new release. I'll let you know as soon as it's done.

**Comment by ashleycaselli** [comment]
@asajim FYI, v1.4.3 has just been released 🎉

**Comment by asajim** [comment]
@ashleycaselli thank you so much

**Comment by ashleycaselli** [comment]
> @ashleycaselli thank you so much

also, I opened a [discussions page](https://github.com/TopQuadrant/shacl/discussions) to discuss about further developments

**Comment by afs** [comment]
#153 can be closed with the release of https://github.com/TopQuadrant/shacl/releases/tag/v1.4.3

**Pull request merged**
