### PR TITLE
Thread safety test. copied validateShapes() to validateShapesThreaded…

### PR DESCRIPTION
**Pull request by beaudet**
… and threaded the contents inside the shapes loop.

### CODE REVIEW

**Comment by HolgerKnublauch** [comment]
Ok I can see the validation report seems to skip certain triples. and it ends up with dangling blank nodes that are detached from the report instance. Probably a multi-threading issue with writing to the Graph. I am not sure whether Jena supports concurrent writes, but I guess the default memory graph does not.

**Comment by afs** [comment]
> I am not sure whether Jena supports concurrent writes, but I guess the default memory graph does not.

Where is this happening?

Jena supports concurrent writes with locks, critical sections (very old) and transactions on datasets.

If you add multiple triples, without a lock, chaos will result even if the data structures are not corrupted.

**Comment by HolgerKnublauch** [comment]
Right, there is no locking code or transactions in place, because the code isn't expecting concurrent execution ATM.

**Comment by beaudet** [comment]
Are transactions needed even for a 100% read only scenario?

On Jan 20, 2022 05:52, Holger Knublauch ***@***.***> wrote:

Right, there is no locking code or transactions in place, because the code isn't expecting concurrent execution ATM.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTopQuadrant%2Fshacl%2Fpull%2F138%23issuecomment-1017362383&data=04%7C01%7C%7C6142e53bbfe240e5565b08d9dc02f609%7C53f6461e95ad4b08a8da973e49ae9312%7C0%7C0%7C637782727543829223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fe63c4I0ynYyTKymQd4VUjrzJjfiYZhozMSxBpLedBg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAS7A7KZHNVSMR3LFU4UF3UW7SO7ANCNFSM5L5KC3KQ&data=04%7C01%7C%7C6142e53bbfe240e5565b08d9dc02f609%7C53f6461e95ad4b08a8da973e49ae9312%7C0%7C0%7C637782727543829223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yG5clRZGZIwIERpfesS76PR02vkSjL%2BmeKEKdIDaqMw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C6142e53bbfe240e5565b08d9dc02f609%7C53f6461e95ad4b08a8da973e49ae9312%7C0%7C0%7C637782727543829223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JUtqc2J%2F%2B2B%2BjKVUnFcy%2B7kDjNoPLIxru0ee%2FI8uXn0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C6142e53bbfe240e5565b08d9dc02f609%7C53f6461e95ad4b08a8da973e49ae9312%7C0%7C0%7C637782727543829223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rjOAWDSU6DJ5Ej5PF2hoILQIYR0tzCu%2FCE3qGOMfs50%3D&reserved=0>.

**Comment by beaudet** [comment]
Ah, when the validation report is created new nodes are added to the validation report graph so that's probably where transactions are needed?

**Comment by HolgerKnublauch** [comment]
The proper long-term refactoring here would probably be to not create the report triples directly but instead create an intermediate Java data structure (that is thread-safe). But that's a larger change. Meanwhile I think this PR can be closed?

**Comment by beaudet** [comment]
+1 on the suggested approach and to closing the PR.

**Pull request closed without merging**
